version: "3"
services:
  ml_bankchurn:
    image: bank_churn:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile.ml_bankchurn
    ports:
      - "8000:8000"
    restart: always
  frontend:
    image: frontend:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8501:8501"
    restart: always
  mlflow:
    image: ubuntu/mlflow:2.1.1_1.0-22.04
    container_name: tracker_mlflow
    restart: always
    ports:
      - "5000:5000"
    entrypoint: mlflow server -h 0.0.0.0 --port 5000
    depends_on:
      - ml_bankchurn
      - frontend
    # Example: https://github.com/Toumash/mlflow-docker/blob/master/docker-compose.yml

networks:
  default:
    name: $NETWORK_NAME
    external: true
